import Foundation

func parameterWordSize(_ parameter: Identifier) -> Int {
    parameter.type == "REAL" ? 2 : 1
}

func parameterLocationAddresses(for procedure: ProcedureIdentifier) -> [(index: Int, addr: Int)] {
    let startAddr = procedure.isFunction ? 3 : 1
    var addr = startAddr + procedure.parameters.reduce(0) { $0 + parameterWordSize($1) }
    return procedure.parameters.indices.map { index in
        addr -= parameterWordSize(procedure.parameters[index])
        return (index: index, addr: addr)
    }
}

private func locationKey(_ location: Location) -> String {
    "\(location.segment):\(location.procedure ?? -1):\(location.lexLevel ?? -1):\(location.addr ?? -1)"
}

private func canonicalLocationLookup(_ locations: Set<Location>) -> [String: Location] {
    Dictionary(uniqueKeysWithValues: locations.map { (locationKey($0), $0) })
}

private func canonicalLocation(
    matching location: Location?,
    in lookup: [String: Location]
) -> Location? {
    guard let location else { return nil }
    return lookup[locationKey(location)] ?? location
}

func bestSignatureLocation(
    in locations: Set<Location>,
    segment: Int,
    procedure: Int,
    addr: Int
) -> Location? {
    locations
        .filter {
            $0.segment == segment
                && $0.procedure == procedure
                && $0.addr == addr
        }
        .max {
            let lhsHasType = !$0.type.isEmpty && $0.type != "UNKNOWN"
            let rhsHasType = !$1.type.isEmpty && $1.type != "UNKNOWN"
            if lhsHasType != rhsHasType {
                return !lhsHasType && rhsHasType
            }
            if $0.typeSource.precedence != $1.typeSource.precedence {
                return $0.typeSource.precedence < $1.typeSource.precedence
            }
            return ($0.lexLevel ?? Int.min) < ($1.lexLevel ?? Int.min)
        }
}

func isAutoGeneratedParameter(_ parameter: Identifier) -> Bool {
    parameter.name.contains(/^PARAM[0-9]+$/)
        && (parameter.type.isEmpty || parameter.type == "UNKNOWN")
        && parameter.typeSource == .unknown
}

func synchronizeProcedureParameters(
    for procedure: ProcedureIdentifier,
    locations: Set<Location>
) -> [TypeConflict] {
    var typeConflicts: [TypeConflict] = []
    let parameterLocations = parameterLocationAddresses(for: procedure)
    var locationIndex = 0
    var removedParametersBeforeCurrent = 0

    while locationIndex < parameterLocations.count {
        let originalParameterIndex = parameterLocations[locationIndex].index
        let currentParameterIndex = originalParameterIndex - removedParametersBeforeCurrent
        guard procedure.parameters.indices.contains(currentParameterIndex) else {
            locationIndex += 1
            continue
        }

        let addr = parameterLocations[locationIndex].addr
        if locationIndex + 1 < parameterLocations.count,
           parameterLocations[locationIndex + 1].addr == addr - 1,
           let realBaseLocation = bestSignatureLocation(
               in: locations,
               segment: procedure.segment,
               procedure: procedure.procedure,
               addr: addr - 1
           ),
           realBaseLocation.type == "REAL" {
            if let conflict = procedure.assignParameterType(
                at: currentParameterIndex,
                "REAL",
                source: realBaseLocation.typeSource,
                location: realBaseLocation,
                evidence: "\(procedure.shortDescription) inferred REAL parameter \(procedure.parameters[currentParameterIndex].name)"
            ) {
                typeConflicts.append(conflict)
            }

            let nextParameterIndex = currentParameterIndex + 1
            if procedure.parameters.indices.contains(nextParameterIndex),
               isAutoGeneratedParameter(procedure.parameters[nextParameterIndex]) {
                procedure.parameters.remove(at: nextParameterIndex)
                removedParametersBeforeCurrent += 1
            }

            locationIndex += 2
            continue
        }

        guard let parameterLocation = bestSignatureLocation(
            in: locations,
            segment: procedure.segment,
            procedure: procedure.procedure,
            addr: addr
        ) else {
            locationIndex += 1
            continue
        }

        if let conflict = procedure.assignParameterType(
            at: currentParameterIndex,
            parameterLocation.type,
            source: parameterLocation.typeSource,
            location: parameterLocation,
            evidence: "\(procedure.shortDescription) inferred parameter \(procedure.parameters[currentParameterIndex].name)"
        ) {
            typeConflicts.append(conflict)
        }

        locationIndex += 1
    }

    return typeConflicts
}

func synchronizeProcedureSignatures(
    procedures: [ProcedureIdentifier],
    locations: Set<Location>
) -> [TypeConflict] {
    var typeConflicts: [TypeConflict] = []

    for procedure in procedures {
        if procedure.isFunction,
           let returnLocation = bestSignatureLocation(
               in: locations,
               segment: procedure.segment,
               procedure: procedure.procedure,
               addr: 1
           ) {
            if let conflict = procedure.assignReturnType(
                returnLocation.type,
                source: returnLocation.typeSource,
                location: returnLocation,
                evidence: "\(procedure.shortDescription) inferred return location"
            ) {
                typeConflicts.append(conflict)
            }
        }

        typeConflicts.append(contentsOf: synchronizeProcedureParameters(
            for: procedure,
            locations: locations
        ))
    }

    return typeConflicts
}

func relabelAutoGeneratedParameters(_ procedure: ProcedureIdentifier) {
    guard procedure.parameters.allSatisfy({ $0.name.contains(/^PARAM[0-9]+$/) }) else {
        return
    }
    for index in procedure.parameters.indices {
        procedure.parameters[index].name = "PARAM\(index + 1)"
    }
}

func applyProcedureSignatureLocations(
    procedures: [ProcedureIdentifier],
    codeSegments: [Int: CodeSegment],
    locations: inout Set<Location>
) -> [TypeConflict] {
    var typeConflicts: [TypeConflict] = []

    func procedureLexLevel(_ identifier: ProcedureIdentifier) -> Int? {
        codeSegments[identifier.segment]?.procedures.first(where: {
            $0.identifier?.segment == identifier.segment
                && $0.identifier?.procedure == identifier.procedure
        })?.lexicalLevel
    }

    func removeLocation(segment: Int, procedure: Int, addr: Int) {
        let existingLocations = locations.filter {
            $0.segment == segment && $0.procedure == procedure && $0.addr == addr
        }
        for existing in existingLocations {
            locations.remove(existing)
        }
    }

    @discardableResult
    func upsertSignatureLocation(
        segment: Int,
        procedure: Int,
        lexLevel: Int?,
        addr: Int,
        name: String,
        type: String,
        typeSource: TypeSource,
        evidence: String
    ) -> Location {
        let existingLocations = locations.filter {
            $0.segment == segment && $0.procedure == procedure && $0.addr == addr
        }
        let existing = existingLocations.max { lhs, rhs in
            let lhsHasSpecificName = !isAutoGeneratedName(lhs.name)
            let rhsHasSpecificName = !isAutoGeneratedName(rhs.name)
            if lhsHasSpecificName != rhsHasSpecificName {
                return !lhsHasSpecificName && rhsHasSpecificName
            }
            if lhs.typeSource.precedence != rhs.typeSource.precedence {
                return lhs.typeSource.precedence < rhs.typeSource.precedence
            }
            return (lhs.lexLevel ?? Int.min) < (rhs.lexLevel ?? Int.min)
        }

        for existingLocation in existingLocations {
            locations.remove(existingLocation)
        }

        if let existing {
            if !isAutoGeneratedName(name) || isAutoGeneratedName(existing.name) {
                existing.name = name
            }
            if let conflict = existing.assignType(
                type,
                source: typeSource,
                evidence: evidence
            ) {
                typeConflicts.append(conflict)
            }
            existing.isParam = true
            if existing.lexLevel == nil {
                existing.lexLevel = lexLevel
            }
            locations.insert(existing)
            return existing
        } else {
            let location = Location(
                segment: segment,
                procedure: procedure,
                lexLevel: lexLevel,
                addr: addr,
                isParam: true,
                name: name,
                type: type,
                typeSource: typeSource
            )
            locations.insert(location)
            return location
        }
    }

    for procedure in procedures {
        relabelAutoGeneratedParameters(procedure)
        let lexLevel = procedureLexLevel(procedure)
        var paramAddr = procedure.isFunction ? 3 : 1
        var parameterLocationsByIndex: [Int: Location] = [:]

        if procedure.isFunction {
            let returnName = procedure.procName ?? procedure.shortDescription
            procedure.returnLocation = upsertSignatureLocation(
                segment: procedure.segment,
                procedure: procedure.procedure,
                lexLevel: lexLevel,
                addr: 1,
                name: returnName,
                type: procedure.returnType ?? "UNKNOWN",
                typeSource: procedure.returnTypeSource,
                evidence: "\(procedure.shortDescription) return"
            )
            if procedure.returnType == "REAL" {
                removeLocation(
                    segment: procedure.segment,
                    procedure: procedure.procedure,
                    addr: 2
                )
            }
        }

        for (parameterIndex, parameter) in procedure.parameters.enumerated().reversed() {
            let location = upsertSignatureLocation(
                segment: procedure.segment,
                procedure: procedure.procedure,
                lexLevel: lexLevel,
                addr: paramAddr,
                name: parameter.name,
                type: parameter.type,
                typeSource: parameter.typeSource,
                evidence: "\(procedure.shortDescription) parameter \(parameter.name)"
            )
            parameterLocationsByIndex[parameterIndex] = location
            if parameter.type == "REAL" {
                removeLocation(
                    segment: procedure.segment,
                    procedure: procedure.procedure,
                    addr: paramAddr + 1
                )
            }
            paramAddr += parameterWordSize(parameter)
        }
        procedure.parameterLocations = procedure.parameters.indices.compactMap {
            parameterLocationsByIndex[$0]
        }
    }

    return typeConflicts
}

func canonicalizeInstructionLocations(
    codeSegments: [Int: CodeSegment],
    locations: Set<Location>
) {
    let lookup = canonicalLocationLookup(locations)
    for (_, codeSeg) in codeSegments {
        for proc in codeSeg.procedures {
            for inst in proc.instructions.values {
                inst.memLocation = canonicalLocation(
                    matching: inst.memLocation,
                    in: lookup
                )
            }
        }
    }
}

private func isAutoGeneratedName(_ name: String) -> Bool {
    name.contains(/^(?:[A-Z0-9_]+\.)?(?:PARAM|FUNC|PROC)[0-9]+$/)
}

func applyInitialProcedureSignatureLocations(
    codeSegments: [Int: CodeSegment],
    allLocations: inout Set<Location>
) -> [TypeConflict] {
    var typeConflicts: [TypeConflict] = []

    for (_, codeSeg) in codeSegments {
        for proc in codeSeg.procedures {
            guard let pt = proc.identifier else { continue }
            var paramAddr = 1

            if pt.isFunction == true {
                if let ret = allLocations.first(where: {
                    $0.segment == pt.segment && $0.procedure == pt.procedure
                        && $0.addr == 1
                }) {
                    ret.name = pt.procName ?? pt.shortDescription
                    if let conflict = ret.assignType(
                        pt.returnType ?? "UNKNOWN",
                        source: pt.returnTypeSource,
                        evidence: "\(pt.shortDescription) return"
                    ) {
                        typeConflicts.append(conflict)
                    }
                    ret.isParam = true
                    allLocations.update(with: ret)
                } else {
                    allLocations.insert(
                        Location(
                            segment: pt.segment,
                            procedure: pt.procedure,
                            lexLevel: proc.lexicalLevel,
                            addr: 1,
                            isParam: true,
                            name: pt.procName ?? pt.shortDescription,
                            type: pt.returnType ?? "UNKNOWN",
                            typeSource: pt.returnTypeSource
                        )
                    )
                }
                if proc.identifier?.returnType == "REAL" {
                    if let ret = allLocations.first(where: {
                        $0.segment == pt.segment
                            && $0.procedure == pt.procedure
                            && $0.addr == 2
                    }) {
                        ret.name = pt.procName ?? pt.shortDescription
                        if let conflict = ret.assignType(
                            pt.returnType ?? "REAL",
                            source: pt.returnTypeSource,
                            evidence: "\(pt.shortDescription) real return"
                        ) {
                            typeConflicts.append(conflict)
                        }
                        ret.isParam = true
                        allLocations.update(with: ret)
                    } else {
                        allLocations.insert(
                            Location(
                                segment: pt.segment,
                                procedure: pt.procedure,
                                lexLevel: proc.lexicalLevel,
                                addr: 2,
                                isParam: true,
                                name: pt.procName ?? pt.shortDescription,
                                type: pt.returnType ?? "REAL",
                                typeSource: pt.returnTypeSource
                            )
                        )
                    }
                }
                paramAddr = 3
            }
            for param in pt.parameters.reversed() {
                if let par = allLocations.first(where: {
                    $0.segment == pt.segment && $0.procedure == pt.procedure
                        && $0.addr == paramAddr
                }) {
                    par.name = param.name
                    if let conflict = par.assignType(
                        param.type,
                        source: param.typeSource,
                        evidence: "\(pt.shortDescription) parameter \(param.name)"
                    ) {
                        typeConflicts.append(conflict)
                    }
                    par.isParam = true
                    allLocations.update(with: par)
                } else {
                    allLocations.insert(
                        Location(
                            segment: pt.segment,
                            procedure: pt.procedure,
                            lexLevel: proc.lexicalLevel,
                            addr: paramAddr,
                            isParam: true,
                            name: param.name,
                            type: param.type,
                            typeSource: param.typeSource
                        )
                    )
                }
                paramAddr += parameterWordSize(param)
            }
        }
    }

    return typeConflicts
}

func synchronizeSignaturesAndLocations(
    allProcedures: [ProcedureIdentifier],
    codeSegments: [Int: CodeSegment],
    allLocations: inout Set<Location>
) -> [TypeConflict] {
    var typeConflicts: [TypeConflict] = []
    typeConflicts.append(contentsOf: synchronizeProcedureSignatures(
        procedures: allProcedures,
        locations: allLocations
    ))
    typeConflicts.append(contentsOf: applyProcedureSignatureLocations(
        procedures: allProcedures,
        codeSegments: codeSegments,
        locations: &allLocations
    ))
    canonicalizeInstructionLocations(
        codeSegments: codeSegments,
        locations: allLocations
    )
    return typeConflicts
}
